// ===================== begin_copyright_notice ============================
//
// Copyright (C) 2023-2025 Intel Corporation
//
// SPDX-License-Identifier: MIT
//
// ===================== end_copyright_notice ==============================

//
// FILE AUTO-GENERATED BY THE GITS CODE GENERATOR. DO NOT MODIFY DIRECTLY.
// GENERATED ON: 2025-03-04 11:48:11.792848
//

#pragma once

#include "directx.h"
#include "enumToStrAuto.h"
#include "guidToStrAuto.h"

#include <string>

namespace gits {
namespace DirectX {

std::string toStr(const wchar_t* s);
std::string callKeyToStr(unsigned key);
std::wstring callKeyToWStr(unsigned key);

} // namespace DirectX
} // namespace gits
