#!/usr/bin/python

# ===================== begin_copyright_notice ============================
#
# Copyright (C) 2023-2026 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
# ===================== end_copyright_notice ==============================

from generator_helpers import generate_file

def generate_files(context, out_path):
    files_to_generate = [
        'statisticsLayerAuto.h',
        'statisticsLayerAuto.cpp',
    ]

    for file_name in files_to_generate:
        generate_plugin_file(context, file_name, out_path)


def generate_plugin_file(context, file_name, out_path):
    import os
    import re
    from mako.template import Template
    from datetime import datetime

    AUTO_GENERATED_HEADER = f"""
//
// FILE AUTO-GENERATED BY THE GITS CODE GENERATOR. DO NOT MODIFY DIRECTLY.
// GENERATED ON: {datetime.now()}
//"""

    mako_script_path = os.path.realpath(out_path + "/codegen/templates/" + file_name + ".mako")
    artifact_file = os.path.realpath(out_path + "/" + file_name)

    base_context = {
        'header': AUTO_GENERATED_HEADER,
    }

    print('Generating file: ' + artifact_file)
    rendered = Template(filename=mako_script_path).render(**(base_context | context))
    rendered = re.sub(r"\r\n", r"\n", rendered)
    with open(artifact_file, 'w') as file:
        file.write(rendered)
