#!/usr/bin/python

# ===================== begin_copyright_notice ============================
#
# Copyright (C) 2023-2026 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
# ===================== end_copyright_notice ==============================

import xml.etree.ElementTree
import re
import os
from datetime import datetime
from mako.template import Template

AUTO_GENERATED_HEADER = f"""
//
// FILE AUTO-GENERATED BY THE GITS CODE GENERATOR. DO NOT MODIFY DIRECTLY.
// GENERATED ON: {datetime.now()}
//"""

def get_full_decl(node):
    comment = node.find("comment")
    if comment is not None:
        node.remove(comment)
    name = node.find("name").text.strip()
    base_type = node.find("type").text.strip()
    parts = []
    if node.text:
      parts.append(node.text.strip())
    for child_node in node:
        if child_node.text:
            parts.append(child_node.text.strip())
        if child_node.tail:
            parts.append(child_node.tail.strip())
    full_type = ' '.join(parts)
    full_type = re.sub(' +', ' ', full_type)
    full_type = full_type.replace(' *', '*')
    full_type = full_type.replace(' :', ':')
    return name, base_type, full_type

def get_length(node):
    length = node.get('altlen') or node.get('len') or ''
    is_null_terminated = 'null-terminated' in length
    length = re.sub(r',?null-terminated', '', length).strip()
    length = [l.strip() for l in length.split(',')] if ',' in length else length
    return length, is_null_terminated

def get_enum_value(enum_node, ext_number=None) -> (int|None):
    value = None
    value_str = enum_node.get('value')
    bitpos = enum_node.get('bitpos')
    if value_str is not None:
        base = 16 if value_str.startswith('0x') else 10
        value = int(value_str, base)
    elif bitpos is not None:
        value = 1 << int(bitpos)
    else:
        extnumber = int(enum_node.get('extnumber')) if enum_node.get('extnumber') is not None else (int(ext_number) if ext_number is not None else 0)
        offset = int(enum_node.get('offset')) if enum_node.get('offset') is not None else 0
        dir = enum_node.get('dir') if enum_node.get('dir') is not None else ''
        value = 1000000000 + (extnumber - 1) * 1000 + offset
        if dir == '-':
            value = -value
    return value

def generate_args(command):
    list = []
    for param in command.params:
        str = f'command.m_{param.name}.Value'
        list.append(str)
    return list

def get_dispatch_table(command):
    dispatch_table_map = {
      'global': 'GetGlobalDispatchTable',
      'instance': 'GetInstanceDispatchTable',
      'device': 'GetDeviceDispatchTable',
    }
    return dispatch_table_map[command.dispatch_level]

def get_define(platform):
    if platform in ['', 'provisional']:
      return ''

    platform_define_map = {
      'win32': 'VK_USE_PLATFORM_WIN32_KHR',
      'xcb': 'VK_USE_PLATFORM_XCB_KHR',
      'xlib': 'VK_USE_PLATFORM_XLIB_KHR',
      'wayland': 'VK_USE_PLATFORM_WAYLAND_KHR'
    }
    return platform_define_map[platform]

def generate_file(context, file_name, out_path):
    in_file = os.path.join("templates", os.path.basename(file_name) + ".mako")
    out_file = os.path.join(out_path, file_name)
    
    base_context = {
        'header': AUTO_GENERATED_HEADER,
        'generate_args': generate_args,
        'get_dispatch_table': get_dispatch_table,
        'get_define': get_define
    }

    print('Generating file: ' + out_file)
    rendered = Template(filename = in_file).render(**(base_context | context))
    rendered = re.sub(r"\r\n", r"\n", rendered)
    with open(out_file, 'w') as file:
        file.write(rendered)
