// ===================== begin_copyright_notice ============================
//
// Copyright (C) 2023-2026 Intel Corporation
//
// SPDX-License-Identifier: MIT
//
// ===================== end_copyright_notice ==============================

/**
* @file   vulkanAccelerationStructureHandler.h
*
* @brief Functions responsible for gathering acceleration structure build inputs
*
*/

#pragma once

#include "vulkanTools.h"

namespace gits {

namespace Vulkan {

namespace {

void PrepareStateRestoreDataForIndexedVertices(CVkDeviceOrHostAddressConstKHRData& structStorage,
                                               VkIndexType indexType,
                                               VkDeviceAddress addressOfIndices,
                                               uint32_t stride,
                                               uint32_t count,
                                               uint32_t firstVertex,
                                               uint32_t maxVertex,
                                               CCommandBufferState& cmdBufState) {
  // The whole vertex data needs to be copied for state restoration purposes. This is done with
  // a compute shader because the source data is provided via a device address and is
  // additionally offset by indices (which are not known).

  // Since we don't know yet how much data would be copied (because we don't know the actual
  // values of indices and a spread between max and min index), we need to prepare storage for
  // maximal potential amount of data. But later on we will know the exact amount (as it is
  // going to be stored by the compute shader).

  // Data copying is performed with an indirect dispatch divided into multiple workgroups, each
  // consisting of multiple local invocations. This is done to speed up copying process as
  // a single compute shader may take too much time to copy all the data and GPU may treat
  // it as a hang. So all in all, the first compute shader gathers the information about the
  // data size and offset and also prepares the number of workgroup count (indirect parameters).
  // The second (indirect) compute shader performs the actual copy operation.

  auto addressOfVertices = structStorage._bufferDeviceAddress._originalDeviceAddress;
  if (!addressOfVertices || !addressOfIndices || !stride || !count) {
    return;
  }

  // Data generated by a compute shader:
  // - DataSize               uint32_t
  // - Offset                 uint32_t
  // - Indirect count x/y/z   uint32_t * 3
  // - Actual vertices        stride * max(count, maxVertex)
  auto size = sizeof(uint32_t) + sizeof(uint32_t) + 3 * sizeof(uint32_t) +
              stride * std::max(count, maxVertex);
  auto commandBuffer = cmdBufState.commandBufferHandle;
  auto device = cmdBufState.commandPoolStateStore->deviceStateStore->deviceHandle;
  auto memoryBufferPair = createTemporaryBuffer(
      device, size, VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT,
      &cmdBufState, VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT);

  auto dstBuffer = memoryBufferPair.second->bufferHandle;
  auto dstMemory = memoryBufferPair.first->deviceMemoryHandle;
  auto descriptorSet = getTemporaryDescriptorSet(device, cmdBufState);
  auto pipelineLayout = SD().internalResources.internalPipelines[device].getLayout();

  {
    VkDescriptorBufferInfo bufferInfo = {
        dstBuffer,    // VkBuffer        buffer;
        0,            // VkDeviceSize    offset;
        VK_WHOLE_SIZE // VkDeviceSize    range;
    };

    VkWriteDescriptorSet writeSet = {
        VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, // VkStructureType                sType
        nullptr,                                // const void                   * pNext
        descriptorSet,                          // VkDescriptorSet                dstSet
        0,                                      // uint32_t                       dstBinding
        0,                                      // uint32_t                       dstArrayElement
        1,                                      // uint32_t                       descriptorCount
        VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,      // VkDescriptorType               descriptorType
        nullptr,                                // const VkDescriptorImageInfo  * pImageInfo
        &bufferInfo,                            // const VkDescriptorBufferInfo * pBufferInfo
        nullptr                                 // const VkBufferView           * pTexelBufferView
    };
    drvVk.vkUpdateDescriptorSets(device, 1, &writeSet, 0, nullptr);
  }

  // Prepare memory barriers, dispatch the compute shaders
  {
    VkMemoryBarrier barrier = {
        VK_STRUCTURE_TYPE_MEMORY_BARRIER,                       // VkStructureType   sType
        nullptr,                                                // const void      * pNext
        VK_ACCESS_MEMORY_WRITE_BIT | VK_ACCESS_MEMORY_READ_BIT, // VkAccessFlags     srcAccessMask
        VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT  // VkAccessFlags     dstAccessMask
    };
    drvVk.vkCmdPipelineBarrier(commandBuffer, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,
                               VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 1, &barrier, 0, nullptr, 0,
                               nullptr);
  }

  {
    VkPipeline prepareIndirectCopyPipeline = VK_NULL_HANDLE;

    switch (indexType) {
    case VK_INDEX_TYPE_UINT16:
      prepareIndirectCopyPipeline = SD().internalResources.internalPipelines[device]
                                        .getPrepareIndirectCopyFor16BitIndexedVerticesPipeline();
      break;
    case VK_INDEX_TYPE_UINT32:
      prepareIndirectCopyPipeline = SD().internalResources.internalPipelines[device]
                                        .getPrepareIndirectCopyFor32BitIndexedVerticesPipeline();
      break;
    default:
      throw std::runtime_error("Invalid index type specified for triangles data!");
    };

    // Look at getPrepareIndirectCopyFor??BitIndexedVerticesShaderModuleSource()
    struct ControlData {
      VkDeviceAddress AddressOfIndices;
      uint32_t Stride;
      uint32_t Count;
      uint32_t FirstVertex;
    } controlData = {addressOfIndices, stride, count, firstVertex};

    drvVk.vkCmdBindPipeline(commandBuffer, VK_PIPELINE_BIND_POINT_COMPUTE,
                            prepareIndirectCopyPipeline);
    drvVk.vkCmdBindDescriptorSets(commandBuffer, VK_PIPELINE_BIND_POINT_COMPUTE, pipelineLayout, 0,
                                  1, &descriptorSet, 0, nullptr);
    drvVk.vkCmdPushConstants(commandBuffer, pipelineLayout, VK_SHADER_STAGE_COMPUTE_BIT, 0,
                             sizeof(controlData), &controlData);
    drvVk.vkCmdDispatch(commandBuffer, 1, 1, 1);
  }

  {
    VkBufferMemoryBarrier barrier = {
        VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER, // VkStructureType sType
        nullptr,                                 // const void    * pNext
        VK_ACCESS_SHADER_WRITE_BIT,              // VkAccessFlags   srcAccessMask
        VK_ACCESS_INDIRECT_COMMAND_READ_BIT | VK_ACCESS_SHADER_READ_BIT |
            VK_ACCESS_SHADER_WRITE_BIT, // VkAccessFlags   dstAccessMask
        VK_QUEUE_FAMILY_IGNORED,        // uint32_t        srcQueueFamilyIndex
        VK_QUEUE_FAMILY_IGNORED,        // uint32_t        dstQueueFamilyIndex
        dstBuffer,                      // VkBuffer        buffer
        0,                              // VkDeviceSize    offset
        5 * sizeof(uint32_t)            // VkDeviceSize    size
    };
    drvVk.vkCmdPipelineBarrier(commandBuffer, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                               VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT |
                                   VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                               0, 0, nullptr, 1, &barrier, 0, nullptr);
  }

  {
    // Look at getPerformIndirectCopyShaderModuleSource()
    struct ControlData {
      VkDeviceAddress VertexData;
    } controlData = {addressOfVertices};
    drvVk.vkCmdBindPipeline(
        commandBuffer, VK_PIPELINE_BIND_POINT_COMPUTE,
        SD().internalResources.internalPipelines[device].getPerformIndirectCopyPipeline());
    drvVk.vkCmdPushConstants(commandBuffer, pipelineLayout, VK_SHADER_STAGE_COMPUTE_BIT, 0,
                             sizeof(controlData), &controlData);
    drvVk.vkCmdDispatchIndirect(commandBuffer, dstBuffer, 2 * sizeof(uint32_t));
  }

  {
    VkMemoryBarrier barrier = {
        VK_STRUCTURE_TYPE_MEMORY_BARRIER,                       // VkStructureType   sType
        nullptr,                                                // const void      * pNext
        VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT, // VkAccessFlags     srcAccessMask
        VK_ACCESS_MEMORY_WRITE_BIT | VK_ACCESS_MEMORY_READ_BIT |
            VK_ACCESS_HOST_READ_BIT // VkAccessFlags     dstAccessMask
    };
    drvVk.vkCmdPipelineBarrier(commandBuffer, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,
                               VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 1, &barrier, 0, nullptr, 0,
                               nullptr);
  }

  if (cmdBufState.currentPipeline != VK_NULL_HANDLE) {
    drvVk.vkCmdBindPipeline(commandBuffer, cmdBufState.currentPipelineBindPoint,
                            cmdBufState.currentPipeline);
  }

  auto fun = [](VkDevice device, VkDeviceMemory memory, VkDeviceSize& offset, VkDeviceSize& size,
                std::vector<uint8_t>& storage) {
    std::vector<uint8_t> temporary(size);
    mapMemoryAndCopyData(temporary.data(), device, memory, 0, size);

    // When vertex data is indexed, acquisition can only be performed via a compute shader. This
    // is caused by the fact that indices can point to arbitrarily large/small offsets within
    // a buffer with vertices. So a compute shader needs to check the minimal and maximal index
    // value and copy data from the found range.

    // Additionally, for GITS to properly handle the data, the compute shader needs to store the
    // actual amount of data that was copied and the calculated offset (minimal index * stride).
    // This is the data the compute shader stores:
    // - uint dataSize;
    // - uint offset;
    // - uint IndirectDispatchX;
    // - uint IndirectDispatchY;
    // - uint IndirectDispatchZ;
    // - uint8_t vertices[];
    auto* basePtr = (uint32_t*)temporary.data();

    size = basePtr[0];   // Data size = stride * ((maxIndex + 1) - minIndex)
    offset = basePtr[1]; // Offset    = minIndex * stride

    // Remove additional control information (a header) from the acquired data and leave only the
    // actual vertex data. (This is done for cohesion with other cases/non-index data).
    storage.resize(size);
    memcpy(storage.data(), temporary.data() + 5 * sizeof(uint32_t), size);
  };

  // Offset doesn't matter at this point as it is going to be calculated by a compute shader.
  structStorage.GatherDataOnQueueSubmitEnd(cmdBufState, fun, device, dstMemory, 0, size);
}

void PrepareStateRestoreData(CVkDeviceOrHostAddressConstKHRData& structStorage,
                             VkDeviceSize deviceAddressOffset,
                             VkDeviceSize size,
                             CCommandBufferState& cmdBufState) {
  // For substream recording, input data used to build acceleration structures
  // needs to be acquired and stored for further use in a state restoration phase.
  // In most cases (i.e. index data, non-indexed triangle geometry, aabbs)
  // data acquisition is very simple and requires only a copy operation.

  auto deviceAddress = structStorage._bufferDeviceAddress._originalDeviceAddress;
  if (!deviceAddress) {
    return;
  }
  auto srcBuffer = findBufferFromDeviceAddress(deviceAddress + deviceAddressOffset);
  if (!srcBuffer) {
    return;
  }
  auto baseAddress = SD()._bufferstates[srcBuffer]->deviceAddress;
  auto bufferOffset = deviceAddress + deviceAddressOffset - baseAddress;

  auto commandBuffer = cmdBufState.commandBufferHandle;
  auto device = cmdBufState.commandPoolStateStore->deviceStateStore->deviceHandle;
  auto memoryBufferPair = createTemporaryBuffer(device, size, VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                                                &cmdBufState, VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT);

  injectCopyCommand(commandBuffer, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,
                    VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, size, srcBuffer, bufferOffset,
                    VK_ACCESS_MEMORY_WRITE_BIT | VK_ACCESS_MEMORY_READ_BIT,
                    VK_ACCESS_MEMORY_WRITE_BIT | VK_ACCESS_MEMORY_READ_BIT,
                    memoryBufferPair.second->bufferHandle, 0, 0, VK_ACCESS_HOST_READ_BIT);

  auto fun = [](VkDevice device, VkDeviceMemory memory, VkDeviceSize& offset, VkDeviceSize& size,
                std::vector<uint8_t>& storage) {
    storage.resize(size);
    mapMemoryAndCopyData(storage.data(), device, memory, 0, size);
  };

  structStorage.GatherDataOnQueueSubmitEnd(cmdBufState, fun, device,
                                           memoryBufferPair.first->deviceMemoryHandle,
                                           deviceAddressOffset, size);
}

} // namespace

inline void handleAccelerationStructureBuild(
    VkCommandBuffer cmdBuf,
    uint32_t infoCount,
    const VkAccelerationStructureBuildGeometryInfoKHR* pInfos,
    const VkAccelerationStructureBuildRangeInfoKHR* const* ppBuildRangeInfos) {
  auto& cmdBufState = *SD()._commandbufferstates[cmdBuf];

  for (uint32_t bgi = 0; bgi < infoCount; ++bgi) {
    // Struct storage data is going to be injected into original structures via pNext
    // that's why a pointer to original, app-provided structures is needed here.
    auto* pBuildGeometryInfo = &pInfos[bgi];
    auto* pBuildRangeInfos = ppBuildRangeInfos[bgi];
    auto& accelerationStructureState =
        SD()._accelerationstructurekhrstates[pBuildGeometryInfo->dstAccelerationStructure];

    std::shared_ptr<CAccelerationStructureKHRState::CBuildInfo> stateTrackInfo;

    // Full acceleration structure build
    if (pBuildGeometryInfo->mode == VK_BUILD_ACCELERATION_STRUCTURE_MODE_BUILD_KHR) {
      stateTrackInfo = std::make_shared<CAccelerationStructureKHRState::CBuildInfo>(
          pBuildGeometryInfo, pBuildRangeInfos);

      accelerationStructureState->buildInfo = stateTrackInfo;
      accelerationStructureState->updateInfo.reset();
      accelerationStructureState->copyInfo.reset();
    }
    // Acceleration structure update (full build info left untouched)
    else if (pBuildGeometryInfo->mode == VK_BUILD_ACCELERATION_STRUCTURE_MODE_UPDATE_KHR) {
      const auto& srcAccelerationStructureState =
          SD()._accelerationstructurekhrstates[pBuildGeometryInfo->srcAccelerationStructure];
      stateTrackInfo = std::make_shared<CAccelerationStructureKHRState::CBuildInfo>(
          pBuildGeometryInfo, pBuildRangeInfos, srcAccelerationStructureState);

      accelerationStructureState->updateInfo = stateTrackInfo;
    }

    std::vector<uint32_t> primitivesCount(pBuildGeometryInfo->geometryCount);

    for (uint32_t g = 0; g < pBuildGeometryInfo->geometryCount; ++g) {
      auto& buildRangeInfo = pBuildRangeInfos[g];

      primitivesCount[g] = buildRangeInfo.primitiveCount;
      if (buildRangeInfo.primitiveCount == 0) {
        continue;
      }

      auto* pStateTrackedGeometry =
          pBuildGeometryInfo->pGeometries
              ? stateTrackInfo->buildGeometryInfoData._pGeometries->Vector()[g].get()
              : stateTrackInfo->buildGeometryInfoData._ppGeometries->Vector()[g][0].get();
      const VkAccelerationStructureGeometryKHR* pGeometry =
          pBuildGeometryInfo->pGeometries ? &pBuildGeometryInfo->pGeometries[g]
                                          : pBuildGeometryInfo->ppGeometries[g];

      switch (pGeometry->geometryType) {
      case VK_GEOMETRY_TYPE_TRIANGLES_KHR: {
        auto& triangles = pGeometry->geometry.triangles;
        auto& stateTrackedTriangles = pStateTrackedGeometry->_geometry->_triangles;

        // Non-indexed geometry
        if (triangles.indexType == VK_INDEX_TYPE_NONE_KHR) {
          // Vertex data
          auto deviceAddressOffset =
              buildRangeInfo.primitiveOffset + buildRangeInfo.firstVertex * triangles.vertexStride;
          auto dataSize = buildRangeInfo.primitiveCount * 3 * triangles.vertexStride;

          PrepareStateRestoreData(*stateTrackedTriangles->_vertexData, deviceAddressOffset,
                                  dataSize, cmdBufState);
        }
        // Indexed geometry
        else {
          // Index data
          {
            auto dataSize =
                buildRangeInfo.primitiveCount * 3 * getIndexElementSize(triangles.indexType);
            PrepareStateRestoreData(*stateTrackedTriangles->_indexData,
                                    buildRangeInfo.primitiveOffset, dataSize, cmdBufState);
          }
          // Vertex data
          PrepareStateRestoreDataForIndexedVertices(
              *stateTrackedTriangles->_vertexData, triangles.indexType,
              triangles.indexData.deviceAddress + buildRangeInfo.primitiveOffset,
              triangles.vertexStride, buildRangeInfo.primitiveCount * 3, buildRangeInfo.firstVertex,
              triangles.maxVertex, cmdBufState);
        }

        // Transform data
        PrepareStateRestoreData(*stateTrackedTriangles->_transformData,
                                buildRangeInfo.transformOffset, sizeof(VkTransformMatrixKHR),
                                cmdBufState);
        break;
      }
      case VK_GEOMETRY_TYPE_AABBS_KHR: {
        // AABBs data
        auto dataSize = sizeof(VkAabbPositionsKHR) * buildRangeInfo.primitiveCount;
        PrepareStateRestoreData(*pStateTrackedGeometry->_geometry->_aabbs->_data,
                                buildRangeInfo.primitiveOffset, dataSize, cmdBufState);
        break;
      }
      case VK_GEOMETRY_TYPE_INSTANCES_KHR: {
        if (pGeometry->geometry.instances.arrayOfPointers) {
          throw std::runtime_error(
              "arrayOfPointers is currently not supported for VK_GEOMETRY_TYPE_INSTANCES_KHR!");
        }
        // Instance data
        auto dataSize = sizeof(VkAccelerationStructureInstanceKHR) * buildRangeInfo.primitiveCount;
        PrepareStateRestoreData(*pStateTrackedGeometry->_geometry->_instances->_data,
                                buildRangeInfo.primitiveOffset, dataSize, cmdBufState);
        break;
      }
      default: {
        throw std::runtime_error("Unknown geometry type provided!");
      }
      }
    }

    drvVk.vkGetAccelerationStructureBuildSizesKHR(
        cmdBufState.commandPoolStateStore->deviceStateStore->deviceHandle,
        VK_ACCELERATION_STRUCTURE_BUILD_TYPE_DEVICE_KHR, pBuildGeometryInfo, primitivesCount.data(),
        &accelerationStructureState->buildSizeInfo);
    cmdBufState.touchedResources.emplace_back(
        (uint64_t)pBuildGeometryInfo->dstAccelerationStructure,
        ResourceType::ACCELERATION_STRUCTURE);
  }
}

} // namespace Vulkan
} // namespace gits
