// ===================== begin_copyright_notice ============================
//
// Copyright (C) 2023-2026 Intel Corporation
//
// SPDX-License-Identifier: MIT
//
// ===================== end_copyright_notice ==============================

#ifndef PNEXT_WRAPPER
#define PNEXT_WRAPPER(STRUCTURE_TYPE, structure, ...)
#endif

#ifndef PNEXT_EXTENDED_WRAPPER
#define PNEXT_EXTENDED_WRAPPER(STRUCTURE_TYPE, structure, ...)
#endif

PNEXT_WRAPPER(VK_STRUCTURE_TYPE_APPLICATION_INFO, VkApplicationInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO, VkBufferCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER, VkBufferMemoryBarrier)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO, VkBufferViewCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO, VkCommandBufferAllocateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO, VkCommandBufferBeginInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO, VkCommandBufferInheritanceInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO, VkCommandPoolCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO, VkComputePipelineCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_COPY_DESCRIPTOR_SET, VkCopyDescriptorSet)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO, VkDescriptorPoolCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO, VkDescriptorSetAllocateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO, VkDescriptorSetLayoutCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO, VkDeviceCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO, VkDeviceQueueCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_EVENT_CREATE_INFO, VkEventCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_FENCE_CREATE_INFO, VkFenceCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO, VkFramebufferCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO, VkGraphicsPipelineCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO, VkImageCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER, VkImageMemoryBarrier)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO, VkImageViewCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO, VkInstanceCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE, VkMappedMemoryRange)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_MEMORY_BARRIER, VkMemoryBarrier)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO,
              VkPipelineCacheCreateInfo,
              _V1) /* <--- watch out for _V1 */
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,
              VkPipelineColorBlendStateCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO,
              VkPipelineDepthStencilStateCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO,
              VkPipelineDynamicStateCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,
              VkPipelineInputAssemblyStateCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO, VkPipelineLayoutCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,
              VkPipelineMultisampleStateCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO,
              VkPipelineRasterizationStateCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, VkPipelineShaderStageCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO,
              VkPipelineTessellationStateCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
              VkPipelineVertexInputStateCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO,
              VkPipelineViewportStateCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PRESENT_INFO_KHR, VkPresentInfoKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO, VkQueryPoolCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO, VkRenderPassBeginInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO, VkRenderPassCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO, VkSamplerCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO, VkSemaphoreCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO, VkShaderModuleCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_SUBMIT_INFO, VkSubmitInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR, VkSwapchainCreateInfoKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR, VkWin32SurfaceCreateInfoKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, VkWriteDescriptorSet)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR, VkXcbSurfaceCreateInfoKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS, VkMemoryDedicatedRequirements)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_INLINE_UNIFORM_BLOCK_CREATE_INFO,
              VkDescriptorPoolInlineUniformBlockCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET_INLINE_UNIFORM_BLOCK,
              VkWriteDescriptorSetInlineUniformBlock)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_FEATURES,
              VkPhysicalDeviceInlineUniformBlockFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_RENDER_PASS_MULTIVIEW_CREATE_INFO, VkRenderPassMultiviewCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_UNIFORM_BUFFER_STANDARD_LAYOUT_FEATURES,
              VkPhysicalDeviceUniformBufferStandardLayoutFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SCALAR_BLOCK_LAYOUT_FEATURES,
              VkPhysicalDeviceScalarBlockLayoutFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_DEVICE_GROUP_SWAPCHAIN_CREATE_INFO_KHR,
              VkDeviceGroupSwapchainCreateInfoKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_DEVICE_GROUP_SUBMIT_INFO, VkDeviceGroupSubmitInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_DEVICE_GROUP_PRESENT_INFO_KHR, VkDeviceGroupPresentInfoKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2, VkPhysicalDeviceFeatures2)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO,
              VkDescriptorSetLayoutBindingFlagsCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO,
              VkDescriptorSetVariableDescriptorCountAllocateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO, VkImageFormatListCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_IMAGE_VIEW_USAGE_CREATE_INFO, VkImageViewUsageCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO, VkMemoryAllocateFlagsInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO,
              VkBindBufferMemoryDeviceGroupInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_DEVICE_GROUP_COMMAND_BUFFER_BEGIN_INFO,
              VkDeviceGroupCommandBufferBeginInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO,
              VkBindImageMemoryDeviceGroupInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO, VkMemoryDedicatedAllocateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENTS_CREATE_INFO,
              VkFramebufferAttachmentsCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_RENDER_PASS_ATTACHMENT_BEGIN_INFO, VkRenderPassAttachmentBeginInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MESH_SHADER_FEATURES_NV,
              VkPhysicalDeviceMeshShaderFeaturesNV)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_8BIT_STORAGE_FEATURES,
              VkPhysicalDevice8BitStorageFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_FEATURES,
              VkPhysicalDeviceDescriptorIndexingFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_SURFACE_FULL_SCREEN_EXCLUSIVE_WIN32_INFO_EXT,
              VkSurfaceFullScreenExclusiveWin32InfoEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_SURFACE_FULL_SCREEN_EXCLUSIVE_INFO_EXT,
              VkSurfaceFullScreenExclusiveInfoEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_SURFACE_CAPABILITIES_FULL_SCREEN_EXCLUSIVE_EXT,
              VkSurfaceCapabilitiesFullScreenExclusiveEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_MEMORY_PRIORITY_ALLOCATE_INFO_EXT, VkMemoryPriorityAllocateInfoEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_IMAGE_STENCIL_USAGE_CREATE_INFO, VkImageStencilUsageCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_BUFFER_CREATE_INFO_NV,
              VkDedicatedAllocationBufferCreateInfoNV)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_IMAGE_CREATE_INFO_NV,
              VkDedicatedAllocationImageCreateInfoNV)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_MEMORY_ALLOCATE_INFO_NV,
              VkDedicatedAllocationMemoryAllocateInfoNV)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_FLOAT16_INT8_FEATURES,
              VkPhysicalDeviceShaderFloat16Int8Features)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_FEATURES,
              VkPhysicalDeviceMultiviewFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES,
              VkPhysicalDevice16BitStorageFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_SAMPLER_REDUCTION_MODE_CREATE_INFO,
              VkSamplerReductionModeCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES,
              VkPhysicalDeviceSamplerYcbcrConversionFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_FEATURES_KHR,
              VkPhysicalDeviceVertexAttributeDivisorFeaturesKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_SEMAPHORE_TYPE_CREATE_INFO, VkSemaphoreTypeCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_TIMELINE_SEMAPHORE_SUBMIT_INFO, VkTimelineSemaphoreSubmitInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_DEPTH_CLIP_STATE_CREATE_INFO_EXT,
              VkPipelineRasterizationDepthClipStateCreateInfoEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TRANSFORM_FEEDBACK_FEATURES_EXT,
              VkPhysicalDeviceTransformFeedbackFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TEXEL_BUFFER_ALIGNMENT_FEATURES_EXT,
              VkPhysicalDeviceTexelBufferAlignmentFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DEMOTE_TO_HELPER_INVOCATION_FEATURES,
              VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_CLIP_ENABLE_FEATURES_EXT,
              VkPhysicalDeviceDepthClipEnableFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CONDITIONAL_RENDERING_FEATURES_EXT,
              VkPhysicalDeviceConditionalRenderingFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_SUBGROUP_EXTENDED_TYPES_FEATURES,
              VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TIMELINE_SEMAPHORE_FEATURES,
              VkPhysicalDeviceTimelineSemaphoreFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES,
              VkPhysicalDeviceBufferDeviceAddressFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES_EXT,
              VkPhysicalDeviceBufferDeviceAddressFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ROBUSTNESS_2_FEATURES_EXT,
              VkPhysicalDeviceRobustness2FeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_HOST_QUERY_RESET_FEATURES,
              VkPhysicalDeviceHostQueryResetFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTENDED_DYNAMIC_STATE_FEATURES_EXT,
              VkPhysicalDeviceExtendedDynamicStateFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CUSTOM_BORDER_COLOR_FEATURES_EXT,
              VkPhysicalDeviceCustomBorderColorFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DRAW_PARAMETERS_FEATURES,
              VkPhysicalDeviceShaderDrawParametersFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_CREATION_FEEDBACK_CREATE_INFO,
              VkPipelineCreationFeedbackCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_SAMPLER_CUSTOM_BORDER_COLOR_CREATE_INFO_EXT,
              VkSamplerCustomBorderColorCreateInfoEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_CREATION_CACHE_CONTROL_FEATURES,
              VkPhysicalDevicePipelineCreationCacheControlFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_SUBPASS_DESCRIPTION_DEPTH_STENCIL_RESOLVE,
              VkSubpassDescriptionDepthStencilResolve)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_BUFFER_OPAQUE_CAPTURE_ADDRESS_CREATE_INFO,
              VkBufferOpaqueCaptureAddressCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_CREATE_INFO_EXT,
              VkBufferDeviceAddressCreateInfoEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PRIORITY_FEATURES_EXT,
              VkPhysicalDeviceMemoryPriorityFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_4444_FORMATS_FEATURES_EXT,
              VkPhysicalDevice4444FormatsFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_LINE_STATE_CREATE_INFO_KHR,
              VkPipelineRasterizationLineStateCreateInfoKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_PROVOKING_VERTEX_STATE_CREATE_INFO_EXT,
              VkPipelineRasterizationProvokingVertexStateCreateInfoEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_DIVISOR_STATE_CREATE_INFO_KHR,
              VkPipelineVertexInputDivisorStateCreateInfoKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_STREAM_CREATE_INFO_EXT,
              VkPipelineRasterizationStateStreamCreateInfoEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INDEX_TYPE_UINT8_FEATURES_KHR,
              VkPhysicalDeviceIndexTypeUint8FeaturesKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROVOKING_VERTEX_FEATURES_EXT,
              VkPhysicalDeviceProvokingVertexFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_LINE_RASTERIZATION_FEATURES_KHR,
              VkPhysicalDeviceLineRasterizationFeaturesKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEDICATED_ALLOCATION_IMAGE_ALIASING_FEATURES_NV,
              VkPhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_MODULE_IDENTIFIER_FEATURES_EXT,
              VkPhysicalDeviceShaderModuleIdentifierFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO, VkPipelineRenderingCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_FEATURES,
              VkPhysicalDeviceVulkan11Features)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES,
              VkPhysicalDeviceVulkan12Features)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_FEATURES,
              VkPhysicalDeviceVulkan13Features)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_SHADER_INTERLOCK_FEATURES_EXT,
              VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_SIZE_CONTROL_FEATURES,
              VkPhysicalDeviceSubgroupSizeControlFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_REQUIRED_SUBGROUP_SIZE_CREATE_INFO,
              VkPipelineShaderStageRequiredSubgroupSizeCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PAGEABLE_DEVICE_LOCAL_MEMORY_FEATURES_EXT,
              VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTENDED_DYNAMIC_STATE_2_FEATURES_EXT,
              VkPhysicalDeviceExtendedDynamicState2FeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_LIBRARY_CREATE_INFO_EXT,
              VkGraphicsPipelineLibraryCreateInfoEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GRAPHICS_PIPELINE_LIBRARY_FEATURES_EXT,
              VkPhysicalDeviceGraphicsPipelineLibraryFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_LIBRARY_CREATE_INFO_KHR, VkPipelineLibraryCreateInfoKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MESH_SHADER_FEATURES_EXT,
              VkPhysicalDeviceMeshShaderFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ATTACHMENT_FEEDBACK_LOOP_LAYOUT_FEATURES_EXT,
              VkPhysicalDeviceAttachmentFeedbackLoopLayoutFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_IMAGE_VIEW_MIN_LOD_CREATE_INFO_EXT, VkImageViewMinLodCreateInfoEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_VIEW_MIN_LOD_FEATURES_EXT,
              VkPhysicalDeviceImageViewMinLodFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_NON_SEAMLESS_CUBE_MAP_FEATURES_EXT,
              VkPhysicalDeviceNonSeamlessCubeMapFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTENDED_DYNAMIC_STATE_3_FEATURES_EXT,
              VkPhysicalDeviceExtendedDynamicState3FeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_SAMPLE_LOCATIONS_STATE_CREATE_INFO_EXT,
              VkPipelineSampleLocationsStateCreateInfoEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_PIPELINE_FEATURES_KHR,
              VkPhysicalDeviceRayTracingPipelineFeaturesKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ACCELERATION_STRUCTURE_FEATURES_KHR,
              VkPhysicalDeviceAccelerationStructureFeaturesKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET_ACCELERATION_STRUCTURE_KHR,
              VkWriteDescriptorSetAccelerationStructureKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_QUERY_FEATURES_KHR,
              VkPhysicalDeviceRayQueryFeaturesKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CLOCK_FEATURES_KHR,
              VkPhysicalDeviceShaderClockFeaturesKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_IMPORT_MEMORY_HOST_POINTER_INFO_EXT,
              VkImportMemoryHostPointerInfoEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_FLOAT_FEATURES_EXT,
              VkPhysicalDeviceShaderAtomicFloatFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SYNCHRONIZATION_2_FEATURES,
              VkPhysicalDeviceSynchronization2Features)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO, VkExportMemoryAllocateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO, VkExternalMemoryImageCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO,
              VkExternalMemoryBufferCreateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DYNAMIC_RENDERING_FEATURES,
              VkPhysicalDeviceDynamicRenderingFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_HOST_IMAGE_COPY_FEATURES_EXT,
              VkPhysicalDeviceHostImageCopyFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_5_FEATURES_KHR,
              VkPhysicalDeviceMaintenance5FeaturesKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_INTEGER_DOT_PRODUCT_FEATURES,
              VkPhysicalDeviceShaderIntegerDotProductFeatures)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MUTABLE_DESCRIPTOR_TYPE_FEATURES_EXT,
              VkPhysicalDeviceMutableDescriptorTypeFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_INVOCATION_REORDER_FEATURES_NV,
              VkPhysicalDeviceRayTracingInvocationReorderFeaturesNV)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_MEMORY_OPAQUE_CAPTURE_ADDRESS_ALLOCATE_INFO,
              VkMemoryOpaqueCaptureAddressAllocateInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_INT64_FEATURES,
              VkPhysicalDeviceShaderAtomicInt64Features)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_ORIGINAL_SHADER_GROUP_HANDLES_GITS,
              VkOriginalShaderGroupHandlesGITS)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_SHADING_RATE_FEATURES_KHR,
              VkPhysicalDeviceFragmentShadingRateFeaturesKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO, VkSamplerYcbcrConversionInfo)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PRESENT_WAIT_FEATURES_KHR,
              VkPhysicalDevicePresentWaitFeaturesKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PRESENT_ID_FEATURES_KHR,
              VkPhysicalDevicePresentIdFeaturesKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PRESENT_ID_KHR, VkPresentIdKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_BIAS_CONTROL_FEATURES_EXT,
              VkPhysicalDeviceDepthBiasControlFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_DEPTH_BIAS_REPRESENTATION_INFO_EXT,
              VkDepthBiasRepresentationInfoEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DYNAMIC_RENDERING_LOCAL_READ_FEATURES_KHR,
              VkPhysicalDeviceDynamicRenderingLocalReadFeaturesKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_4_FEATURES,
              VkPhysicalDeviceMaintenance4Features)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_BUFFER_FEATURES_EXT,
              VkPhysicalDeviceDescriptorBufferFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_SHADER_BARYCENTRIC_FEATURES_KHR,
              VkPhysicalDeviceFragmentShaderBarycentricFeaturesKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_IMAGE_VIEW_SLICED_CREATE_INFO_EXT, VkImageViewSlicedCreateInfoEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DYNAMIC_RENDERING_UNUSED_ATTACHMENTS_FEATURES_EXT,
              VkPhysicalDeviceDynamicRenderingUnusedAttachmentsFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_OPACITY_MICROMAP_FEATURES_EXT,
              VkPhysicalDeviceOpacityMicromapFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_LAYER_SETTINGS_CREATE_INFO_EXT, VkLayerSettingsCreateInfoEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_KHR,
              VkPhysicalDeviceCooperativeMatrixFeaturesKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_BFLOAT16_FEATURES_KHR,
              VkPhysicalDeviceShaderBfloat16FeaturesKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_EXECUTABLE_PROPERTIES_FEATURES_KHR,
              VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_ROBUSTNESS_FEATURES_EXT,
              VkPhysicalDevicePipelineRobustnessFeaturesEXT)
PNEXT_WRAPPER(VK_STRUCTURE_TYPE_PIPELINE_ROBUSTNESS_CREATE_INFO_EXT,
              VkPipelineRobustnessCreateInfoEXT)

// EXTENDED_WRAPPERs accept additional argument passed as a pointer to a custom data
PNEXT_EXTENDED_WRAPPER(VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_TRIANGLES_OPACITY_MICROMAP_EXT,
                       VkAccelerationStructureTrianglesOpacityMicromapEXT)

#undef PNEXT_WRAPPER
#undef PNEXT_EXTENDED_WRAPPER
