// ===================== begin_copyright_notice ============================
//
// Copyright (C) 2023-2026 Intel Corporation
//
// SPDX-License-Identifier: MIT
//
// ===================== end_copyright_notice ==============================

#pragma once

// Include the auto-generated handle argument updaters.
// This file exists as a stable include target; the actual implementations
// are auto-generated by the codegen from handleArgumentUpdatersAuto.h.mako.
#include "handleArgumentUpdatersAuto.h"
#include "handleArgumentUpdatersCustom.h"

#include "captureManager.h"
#include "handleMapService.h"

namespace gits {
namespace vulkan {

template <typename T>
void UpdateHandle(CaptureManager& manager, HandleArgument<T>& arg) {
  if (!arg.Value) {
    return;
  }
  arg.Key = HandleMapService::Get().GetKey(reinterpret_cast<std::uint64_t>(arg.Value));
}

template <typename T>
void UpdateHandle(CaptureManager& manager, HandleArrayArgument<T>& arg) {
  if (!arg.Value) {
    return;
  }
  for (uint32_t i = 0; i < arg.Size; ++i) {
    if (arg.Value[i] != VK_NULL_HANDLE) {
      arg.Keys[i] = HandleMapService::Get().GetKey(reinterpret_cast<std::uint64_t>(arg.Value[i]));
    }
  }
}

template <typename T>
void UpdateOutputHandle(CaptureManager& manager, HandleOutputArgument<T>& arg) {
  if (!arg.Value || !*arg.Value) {
    return;
  }
  arg.Key = manager.CreateHandleKey();
  auto handle = reinterpret_cast<std::uint64_t>(*arg.Value);
  HandleMapService::Get().SetKey(handle, arg.Key);
}

template <typename T>
void UpdateOutputHandle(CaptureManager& manager, HandleArrayOutputArgument<T>& arg) {
  if (!arg.Value || arg.Size == 0) {
    return;
  }
  for (uint32_t i = 0; i < arg.Size; ++i) {
    auto handle = reinterpret_cast<std::uint64_t>(arg.Value[i]);
    GITSKey existingKey = HandleMapService::Get().TryGetKey(handle);
    if (existingKey) {
      arg.Keys[i] = existingKey;
    } else {
      arg.Keys[i] = manager.CreateHandleKey();
      HandleMapService::Get().SetKey(handle, arg.Keys[i]);
    }
  }
}

} // namespace vulkan
} // namespace gits
