// ===================== begin_copyright_notice ============================
//
// Copyright (C) 2023-2026 Intel Corporation
//
// SPDX-License-Identifier: MIT
//
// ===================== end_copyright_notice ==============================

#pragma once

// Include the auto-generated handle argument updaters.
// This file exists as a stable include target; the actual implementations
// are auto-generated by the codegen from handleArgumentUpdatersAuto.h.mako.
#include "handleArgumentUpdatersAuto.h"
#include "handleArgumentUpdatersCustom.h"

#include "captureManager.h"
#include "handleMapService.h"

namespace gits {
namespace vulkan {

template <typename T>
void UpdateHandle(CaptureManager& manager, HandleArgument<T>& arg) {
  if (!arg.Value) {
    return;
  }
  arg.Key = HandleMapService::Get().GetKey(reinterpret_cast<std::uint64_t>(arg.Value));
}

template <typename T>
void UpdateHandle(CaptureManager& manager, HandleArrayArgument<T>& arg) {
  if (!arg.Value) {
    return;
  }
  for (uint32_t i = 0; i < arg.Size; ++i) {
    if (arg.Value[i] != VK_NULL_HANDLE) {
      arg.Keys[i] = HandleMapService::Get().GetKey(reinterpret_cast<std::uint64_t>(arg.Value[i]));
    }
  }
}

// Lenient variants for the *destroy target* of vkDestroy* / vkFree* wrappers.
// Codegen emits these only for the parameter being destroyed; every other
// handle argument (device, parent pool, ...) keeps the strict UpdateHandle.
//
// Rationale: shipped applications occasionally double-destroy a handle (the
// driver typically tolerates it as a no-op), or destroy a handle that is
// already gone from our recorder map for other reasons.  The strict GetKey
// would assert; the lenient path records key=0 (player translates back to
// VK_NULL_HANDLE, which vkDestroy*/vkFree* are required by spec to ignore)
// and lets the call pass through to the driver unchanged.  GetKeyLenient
// emits one classified warning per unique missing handle.
template <typename T>
void UpdateHandleLenient(CaptureManager& manager, HandleArgument<T>& arg) {
  if (!arg.Value) {
    return;
  }
  arg.Key = HandleMapService::Get().GetKeyLenient(reinterpret_cast<std::uint64_t>(arg.Value));
}

template <typename T>
void UpdateHandleLenient(CaptureManager& manager, HandleArrayArgument<T>& arg) {
  if (!arg.Value) {
    return;
  }
  for (uint32_t i = 0; i < arg.Size; ++i) {
    if (arg.Value[i] != VK_NULL_HANDLE) {
      arg.Keys[i] =
          HandleMapService::Get().GetKeyLenient(reinterpret_cast<std::uint64_t>(arg.Value[i]));
    }
  }
}

template <typename T>
void UpdateOutputHandle(CaptureManager& manager, HandleOutputArgument<T>& arg) {
  if (!arg.Value || !*arg.Value) {
    return;
  }
  arg.Key = manager.CreateHandleKey();
  auto handle = reinterpret_cast<std::uint64_t>(*arg.Value);
  HandleMapService::Get().SetKey(handle, arg.Key);
}

template <typename T>
void UpdateOutputHandle(CaptureManager& manager, HandleArrayOutputArgument<T>& arg) {
  if (!arg.Value || arg.Size == 0) {
    return;
  }
  for (uint32_t i = 0; i < arg.Size; ++i) {
    // A null produced handle (e.g. VK_PIPELINE_COMPILE_REQUIRED_EXT or
    // VK_INCOMPATIBLE_SHADER_BINARY_EXT for this batch entry) gets no key:
    // leave Keys[i] at its default null GITSKey and create no mapping. This
    // mirrors the player-side skip added in 665e7991e so the per-index Keys
    // slots stay aligned between record and replay.
    if (!arg.Value[i]) {
      continue;
    }
    auto handle = reinterpret_cast<std::uint64_t>(arg.Value[i]);
    GITSKey existingKey = HandleMapService::Get().TryGetKey(handle);
    if (existingKey) {
      arg.Keys[i] = existingKey;
    } else {
      arg.Keys[i] = manager.CreateHandleKey();
      HandleMapService::Get().SetKey(handle, arg.Keys[i]);
    }
  }
}

} // namespace vulkan
} // namespace gits
