#!/usr/bin/python

# ===================== begin_copyright_notice ============================
#
# Copyright (C) 2023-2026 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
# ===================== end_copyright_notice ==============================

import re
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any

import mako.exceptions
import mako.template

from generator import (
    Api,
    Argument,
    EnumType,
    EnumValue,
    FuncType,
    ReturnValue,
    Token,
    get_enums,
    get_enums_from_xml_data,
)
from reg import Registry
from xml_data_exploration import (
    find_duplicate_enum_values,
    inspect_cross_file_enums,
    inspect_enums,
    print_duplicate_analysis,
)

AUTO_GENERATED_HEADER = f"""
##
## FILE AUTO-GENERATED BY THE GITS CODE GENERATOR. DO NOT MODIFY DIRECTLY.
## GENERATED ON: {datetime.now()}
##
""".strip('\n')

# TODO: Take dirs as arguments, like Vulkan's new generator.py does.
_SCRIPT_DIR = Path(__file__).resolve().parent
_THIRD_PARTY_DIR = _SCRIPT_DIR.parent.parent / 'third_party'
_FILE_TO_API: dict[Path, Api] = {
    _THIRD_PARTY_DIR / 'OpenGL-Registry/xml/gl.xml': Api.GL,
    _THIRD_PARTY_DIR / 'OpenGL-Registry/xml/wgl.xml': Api.WGL,
    _THIRD_PARTY_DIR / 'OpenGL-Registry/xml/glx.xml': Api.GLX,
    _THIRD_PARTY_DIR / 'EGL-Registry/api/egl.xml': Api.EGL,
}


# ---------------------------------------------------------------------------
# Helper functions.
# ---------------------------------------------------------------------------

def mako_render(inpath: str, **kwargs) -> str | None:
    """Render a Mako template into a string."""
    # Objects used by all (or almost all) Mako templates.
    common_objects = {
        'EnumType': EnumType,
        'EnumValue': EnumValue,
        'FuncType': FuncType,
        'Token': Token,
        'Argument': Argument,
        'ReturnValue': ReturnValue,
        'AUTO_GENERATED_HEADER': AUTO_GENERATED_HEADER,
    }

    try:
        print(f"Processing {inpath}...")
        template = mako.template.Template(filename=inpath)
        rendered = template.render(**(common_objects | kwargs))
        rendered = re.sub(r'\r\n', r'\n', rendered)
        return rendered
    except Exception:
        traceback = mako.exceptions.RichTraceback()
        for filename, lineno, function, line in traceback.traceback:
            print(f"{filename}({lineno}) : error in {function}")
            print(line, "\n")
        print(f"{traceback.error.__class__.__name__}: {traceback.error}")
        print(f"Could not render template {Path(inpath).name}, skipping.")
        return None


def mako_write(inpath: str, outpath: str, **kwargs) -> None:
    """Render a Mako template into a file."""
    rendered: str = mako_render(inpath, **kwargs)
    if rendered is None:
        return

    destination = Path('..') / outpath
    with destination.open('w') as fout:
        fout.write(rendered)


def get_enums_from_xml(paths_and_apis: dict[Path, Api]) -> dict[Api, list[EnumValue]]:
    """Load XML registry files, return a dict mapping each to a list of its enums."""
    missing_paths = [path for path in paths_and_apis if not path.is_file()]
    if missing_paths:
        paths = '\n'.join(f'  - {path}' for path in missing_paths)
        raise FileNotFoundError(
            'Missing registry XML files:\n'
            f'{paths}\n'
            'Ensure OpenGL and EGL registries are downloaded in third_party.'
        )

    raw_enums_by_api: dict[Api, list[dict[str, Any]]] = {api: [] for api in Api}

    for path, api in paths_and_apis.items():
        registry = Registry()
        registry.loadFile(str(path))

        raw_enums: list[dict[str, Any]]
        raw_enums = [dict(**e.elem.attrib) for e in registry.enumdict.values()]
        raw_enums_by_api[api] = raw_enums

        # Check for unknown enum attributes.
        novel: set[str] = find_unknown_enum_attributes(raw_enums)
        if novel:
            print(f'WARNING: Unknown enum attributes in {path}: {novel}')

    return get_enums_from_xml_data(raw_enums_by_api)


# ---------------------------------------------------------------------------
# Data tests and sanity checks.
# ---------------------------------------------------------------------------

def test_registry(gl: Registry) -> None:
    """Run various checks on the loaded registry data."""
    # Test aliases.
    # k: str
    # for k, v in gl.enumdict.items():
    #     enum = EnumValue(**v.elem.attrib)
    #     if enum.alias:
    #         match = False
    #         mutual_match = False
    #         for key in gl.enumdict.keys():
    #             if key == enum.alias:
    #                 print(f'Match: {enum.name} aka {enum.alias} = {key}')
    #                 match = True
    #                 if gl.enumdict[key].elem.get('alias') == enum.name:
    #                     mutual_match = True
    #                     print(f'Mutual match: {enum.name} aka {enum.alias} = {key}')
    #         if not match:
    #             print(f'No match: {enum.name} aka {enum.alias}')
    #         if not mutual_match:
    #             print(f'No mutual match: {enum.name} aka {enum.alias}')

    # Test types.
    # for k, v in gl.enumdict.items():
    #     enum = EnumValue(**v.elem.attrib)
    #     if enum.type != EnumType.INT:
    #         print(f'Non-int enum: {enum.name} type={enum.type}')

    # Prepare {value: name} and {name: [EnumValue]} dicts.
    # # values: dict[int, list[EnumValue]] = defaultdict(list)
    # values: dict[int, list[str]] = defaultdict(list)
    # names: dict[str, list[EnumValue]] = defaultdict(list)
    # for k, v in gl.enumdict.items():
    #     enum = EnumValue(**v.elem.attrib)
    #     # values[enum.value].append(enum)
    #     name: str = v.elem.attrib['name']
    #     values[v.elem.attrib['value']].append(name)
    #     names[name].append(enum)
    # # Print values and their associated enums names.
    # for value, enums in values.items():
    #     print(f'{value}: {enums}')

    # Print groups.
    # print('\n\n###### Group dict is empty: ######')
    # # <enums> tags are not considered groups, only <group> tags are.
    # for k, v in gl.groupdict.items():
    #     print(f'{k}: {v}')

    # Check if the group attributes on enums match group data.
    # print('\n\n###### Checking group data: ######')
    # # Can't do it because there is no group data in the registry.
    # for k, v in gl.enumdict.items():
    #     enum = EnumValue(**v.elem.attrib)
    #     print(enum)
    #     groupxml = gl.groupdict[enum.group]
    #     group = EnumGroup(**groupxml.elem.attrib)
    #     print(f'{enum.name} reports group {enum.group}')
    #     print(f'{group.name} contains: {group.enumerators}')
    # Test aliases.
    # k: str
    # for k, v in gl.enumdict.items():
    #     enum = EnumValue(**v.elem.attrib)
    #     if enum.alias:
    #         match = False
    #         mutual_match = False
    #         for key in gl.enumdict.keys():
    #             if key == enum.alias:
    #                 print(f'Match: {enum.name} aka {enum.alias} = {key}')
    #                 match = True
    #                 if gl.enumdict[key].elem.get('alias') == enum.name:
    #                     mutual_match = True
    #                     print(f'Mutual match: {enum.name} aka {enum.alias} = {key}')
    #         if not match:
    #             print(f'No match: {enum.name} aka {enum.alias}')
    #         if not mutual_match:
    #             print(f'No mutual match: {enum.name} aka {enum.alias}')

    # Test types.
    # for k, v in gl.enumdict.items():
    #     enum = EnumValue(**v.elem.attrib)
    #     if enum.type != EnumType.INT:
    #         print(f'Non-int enum: {enum.name} type={enum.type}')

    # Prepare {value: name} and {name: [EnumValue]} dicts.
    # # values: dict[int, list[EnumValue]] = defaultdict(list)
    # values: dict[int, list[str]] = defaultdict(list)
    # names: dict[str, list[EnumValue]] = defaultdict(list)
    # for k, v in gl.enumdict.items():
    #     enum = EnumValue(**v.elem.attrib)
    #     # values[enum.value].append(enum)
    #     name: str = v.elem.attrib['name']
    #     values[v.elem.attrib['value']].append(name)
    #     names[name].append(enum)
    # # Print values and their associated enums names.
    # for value, enums in values.items():
    #     print(f'{value}: {enums}')

    # Print groups.
    # print('\n\n###### Group dict is empty: ######')
    # # <enums> tags are not considered groups, only <group> tags are.
    # for k, v in gl.groupdict.items():
    #     print(f'{k}: {v}')

    # Check if the group attributes on enums match group data.
    # print('\n\n###### Checking group data: ######')
    # # Can't do it because there is no group data in the registry.
    # for k, v in gl.enumdict.items():
    #     enum = EnumValue(**v.elem.attrib)
    #     print(enum)
    #     groupxml = gl.groupdict[enum.group]
    #     group = EnumGroup(**groupxml.elem.attrib)
    #     print(f'{enum.name} reports group {enum.group}')
    #     print(f'{group.name} contains: {group.enumerators}')


def find_unknown_enum_attributes(raw_enums: list[dict[str, Any]]) -> set[str]:
    """Return attributes on enums that aren't on the known list."""
    known_attribs = set(EnumValue.__dataclass_fields__.keys())
    known_attribs.remove('groups')
    known_attribs.add('group') # XMLs use 'group', our EnumValue uses 'groups'.

    novel = set()
    for enum_dict in raw_enums:
        for attrib in enum_dict.keys():
            if attrib not in known_attribs:
                novel.add(attrib)

    return novel


def identify_enum_groups(enums: list[EnumValue]) -> dict[str, int]:
    """Gather all encountered group names and count their occurrences."""
    # TODO: perhaps just use Counter?
    result: dict[str, int] = defaultdict(int)

    for enum in enums:
        for group_name in enum.groups:
            result[group_name] += 1

    return result


def sort_enums_by_group(enums: list[EnumValue]) -> dict[str, list[EnumValue]]:
    """Return a dict with group name as key and enums from this group as value."""
    result: dict[str, list[EnumValue]] = defaultdict(list)

    for enum in enums:
        if not enum.groups:
            result[''].append(enum)
        for group_name in enum.groups:
            result[group_name].append(enum)

    return result


def detect_duplicate_enum_values(enums: list[EnumValue]) -> None:
    """Find enums that are not uniquely identified by a (value, group) tuple."""
    analysis: list[Any] = find_duplicate_enum_values(enums)
    print_duplicate_analysis(analysis)
    # # Old code:
    # enums_by_value_and_group: dict[(str, str), list[EnumValue]] = defaultdict(list)
    # for enum in enums:
    #     if not enum.groups:
    #         enums_by_value_and_group[enum.value, ''].append(enum)
    #     for group in enum.groups:
    #         enums_by_value_and_group[enum.value, group].append(enum)
    #
    # # Detect duplicate enum values that can't be distinguished by group.
    # # TODO: Convert values from str to int to spot same values written differently.
    # # TODO: Make use of the alias field to spot duplicates that are actually aliases.
    # enum_values_by_group: dict[str, list[EnumValue]] = sort_enums_by_group(enums)
    #
    # print("####### Enum values duplicated within groups: #######")
    # # TODO: Would it be better to store whole enums here instead of just their values?
    # for group, values in enum_values_by_group.items():
    #     duplicate_values: list[str] = [k for k,v in Counter(values).items() if v > 1]
    #     dupes_with_names: list[str] = []
    #     for value in duplicate_values:
    #         enums: list[EnumValue] = enums_by_value_and_group[value, group]
    #         assert len(enums) >= 1, \
    #             f"Duplicate value {value} should have multiple corresponding enums but only has: {enums}."
    #
    #         # Most of the duplicates are due to vendor suffixes (FOO vs FOO_ARB).
    #         # Let's collapse those and focus on real duplicates.
    #         # New dedupe code.
    #         enums_by_generic_name: dict[str, list[EnumValue]] = defaultdict(list)
    #         for enum in enums:
    #             enums_by_generic_name[generic_name(enum)].append(enum)
    #
    #         # Old dedupe code.
    #         generic_enum_names: list[str] = [generic_name(e) for e in enums]
    #         unique_names: list[str] = list(set(generic_enum_names))
    #         if len(unique_names) < 2:
    #             continue
    #
    #         names: str = ', '.join(unique_names)
    #         dupes_with_names.append(f'{value}: [{names}]')
    #
    #     if dupes_with_names:
    #         print(f"Group {group} has {len(dupes_with_names)} duplicates:\n    {'\n    '.join(dupes_with_names)}\n")


def two_way_list_diff(list_a: list[Any], list_b: list[Any]) -> tuple[list[Any], list[Any]]:
    """Return tuple of items only in list_a and items only in list_b."""
    set_a: set[Any] = set(list_a)
    set_b: set[Any] = set(list_b)
    # Using list.index as key preserves original order.
    # TODO: list.index has O(n) complexity, consider using a better method.
    only_in_set_a = sorted(set_a - set_b, key=list_a.index)
    only_in_set_b = sorted(set_b - set_a, key=list_b.index)
    return only_in_set_a, only_in_set_b


def diff_xml_and_generator_enums(
    xml_enums: dict[Api, list[EnumValue]],
    generator_enums: dict[Api, list[EnumValue]],
) -> None:
    """Diff enums from XML with those from legacy generator data."""
    only_in_xml: dict[Api, list[EnumValue]] = {}
    only_in_generator: dict[Api, list[EnumValue]] = {}

    for api in Api:
        xml_list: list[EnumValue] = xml_enums.get(api, [])
        generator_list: list[EnumValue] = generator_enums.get(api, [])

        enums_only_in_generator: list[EnumValue]
        enums_only_in_xml: list[EnumValue]
        enums_only_in_generator, enums_only_in_xml = two_way_list_diff(generator_list, xml_list)

        if enums_only_in_xml:
            only_in_xml[api] = enums_only_in_xml
        if enums_only_in_generator:
            only_in_generator[api] = enums_only_in_generator

    if only_in_xml:
        print("####### Enums only present in XML #######")
        print(mako_render('templates/meta_enums.mako', enums_by_api=only_in_xml))
    if only_in_generator:
        print("####### Enums only present in generator #######")
        print(mako_render('templates/meta_enums.mako', enums_by_api=only_in_generator))


# ---------------------------------------------------------------------------
# Main function.
# ---------------------------------------------------------------------------

def main() -> None:
    """Update the OpenGL generator data based on gl.xml and similar files."""
    enums_from_xml: dict[Api, list[EnumValue]] = get_enums_from_xml(_FILE_TO_API)

    # Detect differences between XML enums and generator enums.
    generator_enums: dict[Api, list[EnumValue]] = get_enums()

    diff_xml_and_generator_enums(enums_from_xml, generator_enums)

    # Detect collisions - enums that have the same value and group.
    for api, api_enums in enums_from_xml.items():
        # print(f"\n\n\n        {api}        \n\n\n")
        # Old OpenGL backend will need few if any data updates, new backend won't
        # even store the data in intermediate form. This is why we don't bother
        # updating detect_duplicate_enum_values to support CANONICAL_NAME_OVERRIDES
        # from generate_gl.py or running it by default. It can be run manually
        # if we know we need to update enum data.
        # detect_duplicate_enum_values(api_enums)
        inspect_enums(api, api_enums)
    inspect_cross_file_enums(enums_from_xml)

    mako_write('templates/meta_enums.mako', 'meta_enums.py', enums_by_api=enums_from_xml)


if __name__ == '__main__':
    main()
