#!/usr/bin/python

# ===================== begin_copyright_notice ============================
#
# Copyright (C) 2023-2026 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
# ===================== end_copyright_notice ==============================

# This script takes GL registry files (XML) and outputs their data in an
# intermediate format ingested by the old OpenGL code generator. New generator
# will be based on it, but won't save the intermediate format on disk.

import re
import sys  # For sys.path.insert.
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any

import mako.exceptions
import mako.template

from generator import (
    Api,
    Argument,
    EnumType,
    EnumValue,
    FuncType,
    ReturnValue,
    Token,
    get_enums,
    get_tokens,
    get_enums_from_xml_data,
    get_functions_from_xml_data,
)

# Add the OpenGL-Registry/xml directory to sys.path so we can import reg.py.
_THIRD_PARTY_DIR = Path(__file__).resolve().parents[2] / 'third_party'
sys.path.insert(0, str(_THIRD_PARTY_DIR / 'OpenGL-Registry/xml'))

from reg import Registry
from xml_data_exploration import (
    find_duplicate_enum_values,
    inspect_cross_file_enums,
    inspect_enums,
    inspect_functions,
    inspect_function_params,
    check_function_groups_against_enums,
    print_duplicate_analysis,
)

AUTO_GENERATED_HEADER = f"""
##
## FILE AUTO-GENERATED BY THE GITS CODE GENERATOR. DO NOT MODIFY DIRECTLY.
## GENERATED ON: {datetime.now()}
##
""".strip('\n')

# TODO: Take dirs as arguments, like Vulkan's new generator.py does.
_FILE_TO_API: dict[Path, Api] = {
    _THIRD_PARTY_DIR / 'OpenGL-Registry/xml/gl.xml': Api.GL,
    _THIRD_PARTY_DIR / 'OpenGL-Registry/xml/wgl.xml': Api.WGL,
    _THIRD_PARTY_DIR / 'OpenGL-Registry/xml/glx.xml': Api.GLX,
    _THIRD_PARTY_DIR / 'EGL-Registry/api/egl.xml': Api.EGL,
}


# ---------------------------------------------------------------------------
# Helper functions.
# ---------------------------------------------------------------------------

def mako_render(inpath: str, **kwargs) -> str | None:
    """Render a Mako template into a string."""
    # Objects used by all (or almost all) Mako templates.
    common_objects: dict[str, Any] = {
        'EnumType': EnumType,
        'EnumValue': EnumValue,
        'FuncType': FuncType,
        'Token': Token,
        'Argument': Argument,
        'ReturnValue': ReturnValue,
        'AUTO_GENERATED_HEADER': AUTO_GENERATED_HEADER,
    }

    try:
        print(f"Processing {inpath}...")
        template = mako.template.Template(filename=inpath)
        rendered = template.render(**(common_objects | kwargs))
        rendered = re.sub(r'\r\n', r'\n', rendered)
        return rendered
    except Exception:
        traceback = mako.exceptions.RichTraceback()
        for filename, lineno, function, line in traceback.traceback:
            print(f"{filename}({lineno}) : error in {function}")
            print(line, "\n")
        print(f"{traceback.error.__class__.__name__}: {traceback.error}")
        print(f"Could not render template {Path(inpath).name}, skipping.")
        return None


def mako_write(inpath: str, outpath: str, **kwargs) -> None:
    """Render a Mako template into a file."""
    rendered: str = mako_render(inpath, **kwargs)
    if rendered is None:
        return

    destination = Path('..') / outpath
    with destination.open('w') as fout:
        fout.write(rendered)


def normalize_type(type_text: str) -> str:
    """Normalize whitespace in reconstructed C/C++ type text."""
    text = re.sub(r'\s+', ' ', type_text).strip()
    # Ensure single space before asterisk (or a group of them).
    return re.sub(r'\s*(\*+)', r' \1', text)


def reconstruct_type_from_xml_elem(elem: Any) -> str:
    """Reconstruct declaration type text from XML mixed content before <name>.

    XML proto and param elements split C declarations across text nodes, an
    optional <ptype> child, and their tails. This function joins everything up
    to the <name> child and normalizes whitespace to recover the type string
    (e.g. 'const void *') used for the Token's return value and argument types.
    """
    fragments: list[str] = []
    if elem.text:
        fragments.append(elem.text)

    for child in elem:
        if child.tag == 'name':
            break
        if child.text:
            fragments.append(child.text)
        if child.tail:
            fragments.append(child.tail)

    return normalize_type(''.join(fragments))


def extract_functions_from_registry(registry: Registry) -> list[dict[str, Any]]:
    """Extract raw function data from a registry's cmddict.

    For each <command> returns a dict with:
      - 'command_attribs': <command> attributes ('name' injected by reg.py plus
        an optional 'comment').
      - 'return_value': {'type': return type reconstructed from <proto>, 'attribs':
        <proto> attributes (group/class/kind)}.
      - 'params': list of {'name', 'type', 'attribs'}, where 'attribs' are the
        <param> attributes (group/class/kind/len).
      - 'alias_attribs': <alias> attributes (the aliased command's 'name').

    Type strings are reconstructed from each element's mixed content (everything
    before its <name> child). The <glx>/<vecequiv> child elements and the info
    reg.py derives from them are ignored.
    """
    raw_functions: list[dict[str, Any]] = []

    for cmd_obj in registry.cmddict.values():
        cmd_elem = cmd_obj.elem
        proto_elem = cmd_elem.find('proto')
        alias_elem = cmd_elem.find('alias')

        cmd_name = cmd_elem.attrib.get('name')
        if cmd_name is None:
            raise ValueError("<command> element has no 'name' attribute")
        if proto_elem is None:
            raise ValueError(f"<command> '{cmd_name}' has no <proto> element")

        params: list[dict[str, Any]] = []
        for param_elem in cmd_elem.findall('param'):
            name_elem = param_elem.find('name')
            if name_elem is None:
                raise ValueError(f"<param> in command '{cmd_name}' has no <name> element")
            params.append({
                'name': name_elem.text or '',
                'type': reconstruct_type_from_xml_elem(param_elem),
                'attribs': dict(param_elem.attrib),
            })

        raw_functions.append({
            'command_attribs': dict(cmd_elem.attrib),
            'return_value': {
                'type': reconstruct_type_from_xml_elem(proto_elem),
                'attribs': dict(proto_elem.attrib),
            },
            'params': params,
            'alias_attribs': dict(alias_elem.attrib) if alias_elem is not None else {},
        })

    return raw_functions


def load_registries_and_extract_xml_data(paths_and_apis: dict[Path, Api]) -> tuple[dict[Api, list[EnumValue]], dict[Api, list[Token]]]:
    """Load XML registry files, return (enums_by_api, functions_by_api)."""
    missing_paths = [path for path in paths_and_apis if not path.is_file()]
    if missing_paths:
        paths = '\n'.join(f'  - {path}' for path in missing_paths)
        raise FileNotFoundError(
            'Missing registry XML files:\n'
            f'{paths}\n'
            'Ensure OpenGL and EGL registries are downloaded in third_party.'
        )

    raw_enums_by_api: dict[Api, list[dict[str, Any]]] = {api: [] for api in Api}
    raw_functions_by_api: dict[Api, list[dict[str, Any]]] = {api: [] for api in Api}

    for path, api in paths_and_apis.items():
        registry = Registry()
        registry.loadFile(path)

        # Extract enums.
        raw_enums: list[dict[str, Any]]
        raw_enums = [dict(**e.elem.attrib) for e in registry.enumdict.values()]
        raw_enums_by_api[api] = raw_enums

        # Check for unknown enum attributes.
        novel_enum_attribs: set[str] = find_unknown_enum_attributes(raw_enums)
        if novel_enum_attribs:
            print(f'WARNING: Unknown enum attributes in {path}: {novel_enum_attribs}')

        # Extract functions.
        raw_functions: list[dict[str, Any]] = extract_functions_from_registry(registry)
        raw_functions_by_api[api] = raw_functions

        # Check for unknown function attributes.
        novel_func_attribs: set[str] = find_unknown_function_attributes(raw_functions)
        if novel_func_attribs:
            print(f'WARNING: Unknown function attributes in {path}: {sorted(novel_func_attribs)}')

    # Convert raw enums to EnumValue objects.
    enums_by_api = get_enums_from_xml_data(raw_enums_by_api)

    # Convert raw functions to Token objects.
    functions_by_api = get_functions_from_xml_data(raw_functions_by_api)

    return enums_by_api, functions_by_api


# ---------------------------------------------------------------------------
# Data tests and sanity checks.
# ---------------------------------------------------------------------------

def test_registry(gl: Registry) -> None:
    """Run various checks on the loaded registry data."""
    # Test aliases.
    # k: str
    # for k, v in gl.enumdict.items():
    #     enum = EnumValue(**v.elem.attrib)
    #     if enum.alias:
    #         match = False
    #         mutual_match = False
    #         for key in gl.enumdict.keys():
    #             if key == enum.alias:
    #                 print(f'Match: {enum.name} aka {enum.alias} = {key}')
    #                 match = True
    #                 if gl.enumdict[key].elem.get('alias') == enum.name:
    #                     mutual_match = True
    #                     print(f'Mutual match: {enum.name} aka {enum.alias} = {key}')
    #         if not match:
    #             print(f'No match: {enum.name} aka {enum.alias}')
    #         if not mutual_match:
    #             print(f'No mutual match: {enum.name} aka {enum.alias}')

    # Test types.
    # for k, v in gl.enumdict.items():
    #     enum = EnumValue(**v.elem.attrib)
    #     if enum.type != EnumType.INT:
    #         print(f'Non-int enum: {enum.name} type={enum.type}')

    # Prepare {value: name} and {name: [EnumValue]} dicts.
    # # values: dict[int, list[EnumValue]] = defaultdict(list)
    # values: dict[int, list[str]] = defaultdict(list)
    # names: dict[str, list[EnumValue]] = defaultdict(list)
    # for k, v in gl.enumdict.items():
    #     enum = EnumValue(**v.elem.attrib)
    #     # values[enum.value].append(enum)
    #     name: str = v.elem.attrib['name']
    #     values[v.elem.attrib['value']].append(name)
    #     names[name].append(enum)
    # # Print values and their associated enums names.
    # for value, enums in values.items():
    #     print(f'{value}: {enums}')

    # Print groups.
    # print('\n\n###### Group dict is empty: ######')
    # # <enums> tags are not considered groups, only <group> tags are.
    # for k, v in gl.groupdict.items():
    #     print(f'{k}: {v}')

    # Check if the group attributes on enums match group data.
    # print('\n\n###### Checking group data: ######')
    # # Can't do it because there is no group data in the registry.
    # for k, v in gl.enumdict.items():
    #     enum = EnumValue(**v.elem.attrib)
    #     print(enum)
    #     groupxml = gl.groupdict[enum.group]
    #     group = EnumGroup(**groupxml.elem.attrib)
    #     print(f'{enum.name} reports group {enum.group}')
    #     print(f'{group.name} contains: {group.enumerators}')
    # Test aliases.
    # k: str
    # for k, v in gl.enumdict.items():
    #     enum = EnumValue(**v.elem.attrib)
    #     if enum.alias:
    #         match = False
    #         mutual_match = False
    #         for key in gl.enumdict.keys():
    #             if key == enum.alias:
    #                 print(f'Match: {enum.name} aka {enum.alias} = {key}')
    #                 match = True
    #                 if gl.enumdict[key].elem.get('alias') == enum.name:
    #                     mutual_match = True
    #                     print(f'Mutual match: {enum.name} aka {enum.alias} = {key}')
    #         if not match:
    #             print(f'No match: {enum.name} aka {enum.alias}')
    #         if not mutual_match:
    #             print(f'No mutual match: {enum.name} aka {enum.alias}')

    # Test types.
    # for k, v in gl.enumdict.items():
    #     enum = EnumValue(**v.elem.attrib)
    #     if enum.type != EnumType.INT:
    #         print(f'Non-int enum: {enum.name} type={enum.type}')

    # Prepare {value: name} and {name: [EnumValue]} dicts.
    # # values: dict[int, list[EnumValue]] = defaultdict(list)
    # values: dict[int, list[str]] = defaultdict(list)
    # names: dict[str, list[EnumValue]] = defaultdict(list)
    # for k, v in gl.enumdict.items():
    #     enum = EnumValue(**v.elem.attrib)
    #     # values[enum.value].append(enum)
    #     name: str = v.elem.attrib['name']
    #     values[v.elem.attrib['value']].append(name)
    #     names[name].append(enum)
    # # Print values and their associated enums names.
    # for value, enums in values.items():
    #     print(f'{value}: {enums}')

    # Print groups.
    # print('\n\n###### Group dict is empty: ######')
    # # <enums> tags are not considered groups, only <group> tags are.
    # for k, v in gl.groupdict.items():
    #     print(f'{k}: {v}')

    # Check if the group attributes on enums match group data.
    # print('\n\n###### Checking group data: ######')
    # # Can't do it because there is no group data in the registry.
    # for k, v in gl.enumdict.items():
    #     enum = EnumValue(**v.elem.attrib)
    #     print(enum)
    #     groupxml = gl.groupdict[enum.group]
    #     group = EnumGroup(**groupxml.elem.attrib)
    #     print(f'{enum.name} reports group {enum.group}')
    #     print(f'{group.name} contains: {group.enumerators}')


def find_unknown_function_attributes(raw_functions: list[dict[str, Any]]) -> set[str]:
    """Return XML attributes on functions (and their children) not on the known list.

    Inspects XML attributes on <command> and its children (<proto>, <param>, and <alias>;
    <glx> is ignored). Anything not on the allowlists below is reported so we notice
    new/unexpected attributes when the registries change.

    Attributes encountered across the four registries (gl/wgl/glx/egl):
        | element  | gl.xml                  | wgl.xml | glx.xml | egl.xml |
        |----------|-------------------------|---------|---------|---------|
        | command  | name*, comment          | name*   | name*   | name*   |
        | proto    | group, class, kind      | -       | -       | -       |
        | param    | group, class, kind, len | -       | -       | -       |
        | alias    | name                    | -       | -       | name    |

    Note: <command> has no 'name' attribute in the XML files; reg.py injects it based on
    <proto>'s <name>.
    """
    known_command_attribs: set[str] = {
        'name',  # reg.py injects this from <proto><name>; not present in the XML.
        'comment',
    }
    known_proto_attribs: set[str] = {
        'group',
        'class',
        'kind',
    }
    known_param_attribs: set[str] = {
        'group',
        'class',
        'kind',
        'len',
    }
    known_alias_attribs: set[str] = {
        'name',
    }

    novel: set[str] = set()

    for func in raw_functions:
        for attrib in func['command_attribs']:
            if attrib not in known_command_attribs:
                novel.add(f'command:{attrib}')
        for attrib in func['return_value']['attribs']:
            if attrib not in known_proto_attribs:
                novel.add(f'proto:{attrib}')
        for param in func['params']:
            for attrib in param['attribs']:
                if attrib not in known_param_attribs:
                    novel.add(f'param:{attrib}')
        for attrib in func['alias_attribs']:
            if attrib not in known_alias_attribs:
                novel.add(f'alias:{attrib}')

    return novel


def find_unknown_enum_attributes(raw_enums: list[dict[str, Any]]) -> set[str]:
    """Return attributes on enums that aren't on the known list."""
    known_attribs = set(EnumValue.__dataclass_fields__.keys())
    known_attribs.remove('groups')
    known_attribs.add('group') # XMLs use 'group', our EnumValue uses 'groups'.

    novel: set[str] = set()
    for enum_dict in raw_enums:
        for attrib in enum_dict.keys():
            if attrib not in known_attribs:
                novel.add(attrib)

    return novel


def identify_enum_groups(enums: list[EnumValue]) -> dict[str, int]:
    """Gather all encountered group names and count their occurrences."""
    # TODO: perhaps just use Counter?
    result: dict[str, int] = defaultdict(int)

    for enum in enums:
        for group_name in enum.groups:
            result[group_name] += 1

    return result


def sort_enums_by_group(enums: list[EnumValue]) -> dict[str, list[EnumValue]]:
    """Return a dict with group name as key and enums from this group as value."""
    result: dict[str, list[EnumValue]] = defaultdict(list)

    for enum in enums:
        if not enum.groups:
            result[''].append(enum)
        for group_name in enum.groups:
            result[group_name].append(enum)

    return result


def detect_duplicate_enum_values(enums: list[EnumValue]) -> None:
    """Find enums that are not uniquely identified by a (value, group) tuple."""
    analysis: list[Any] = find_duplicate_enum_values(enums)
    print_duplicate_analysis(analysis)
    # # Old code:
    # enums_by_value_and_group: dict[(str, str), list[EnumValue]] = defaultdict(list)
    # for enum in enums:
    #     if not enum.groups:
    #         enums_by_value_and_group[enum.value, ''].append(enum)
    #     for group in enum.groups:
    #         enums_by_value_and_group[enum.value, group].append(enum)
    #
    # # Detect duplicate enum values that can't be distinguished by group.
    # # TODO: Convert values from str to int to spot same values written differently.
    # # TODO: Make use of the alias field to spot duplicates that are actually aliases.
    # enum_values_by_group: dict[str, list[EnumValue]] = sort_enums_by_group(enums)
    #
    # print("####### Enum values duplicated within groups: #######")
    # # TODO: Would it be better to store whole enums here instead of just their values?
    # for group, values in enum_values_by_group.items():
    #     duplicate_values: list[str] = [k for k,v in Counter(values).items() if v > 1]
    #     dupes_with_names: list[str] = []
    #     for value in duplicate_values:
    #         enums: list[EnumValue] = enums_by_value_and_group[value, group]
    #         assert len(enums) >= 1, \
    #             f"Duplicate value {value} should have multiple corresponding enums but only has: {enums}."
    #
    #         # Most of the duplicates are due to vendor suffixes (FOO vs FOO_ARB).
    #         # Let's collapse those and focus on real duplicates.
    #         # New dedupe code.
    #         enums_by_generic_name: dict[str, list[EnumValue]] = defaultdict(list)
    #         for enum in enums:
    #             enums_by_generic_name[generic_name(enum)].append(enum)
    #
    #         # Old dedupe code.
    #         generic_enum_names: list[str] = [generic_name(e) for e in enums]
    #         unique_names: list[str] = list(set(generic_enum_names))
    #         if len(unique_names) < 2:
    #             continue
    #
    #         names: str = ', '.join(unique_names)
    #         dupes_with_names.append(f'{value}: [{names}]')
    #
    #     if dupes_with_names:
    #         print(f"Group {group} has {len(dupes_with_names)} duplicates:\n    {'\n    '.join(dupes_with_names)}\n")


def two_way_list_diff(list_a: list[Any], list_b: list[Any]) -> tuple[list[Any], list[Any]]:
    """Return tuple of items only in list_a and items only in list_b."""
    set_a: set[Any] = set(list_a)
    set_b: set[Any] = set(list_b)
    # Using list.index as key preserves original order.
    # TODO: list.index has O(n) complexity, consider using a better method.
    only_in_set_a = sorted(set_a - set_b, key=list_a.index)
    only_in_set_b = sorted(set_b - set_a, key=list_b.index)
    return only_in_set_a, only_in_set_b


def diff_xml_and_generator_enums(
    xml_enums: dict[Api, list[EnumValue]],
    generator_enums: dict[Api, list[EnumValue]],
) -> None:
    """Diff enums from XML with those from legacy generator data."""
    only_in_xml: dict[Api, list[EnumValue]] = {}
    only_in_generator: dict[Api, list[EnumValue]] = {}

    for api in Api:
        xml_list: list[EnumValue] = xml_enums.get(api, [])
        generator_list: list[EnumValue] = generator_enums.get(api, [])

        enums_only_in_generator: list[EnumValue]
        enums_only_in_xml: list[EnumValue]
        enums_only_in_generator, enums_only_in_xml = two_way_list_diff(generator_list, xml_list)

        if enums_only_in_xml:
            only_in_xml[api] = enums_only_in_xml
        if enums_only_in_generator:
            only_in_generator[api] = enums_only_in_generator

    if only_in_xml:
        print("####### Enums only present in XML #######")
        print(mako_render('templates/meta_enums.py.mako', enums_by_api=only_in_xml))
    if only_in_generator:
        print("####### Enums only present in generator #######")
        print(mako_render('templates/meta_enums.py.mako', enums_by_api=only_in_generator))


TokenDifferencesType = dict[str, tuple[Any, Any]]  # Field name -> (xml value, generator value)

def compare_function_tokens(xml_token: Token, generator_token: Token) -> TokenDifferencesType:
    """Return the XML-vs-generator differences for the core function signature."""
    differences: TokenDifferencesType = {}

    if xml_token.name != generator_token.name:
        differences['name'] = (xml_token.name, generator_token.name)
    if xml_token.alias != generator_token.alias:
        differences['alias'] = (xml_token.alias, generator_token.alias)
    xml_retval_type = normalize_type(xml_token.return_value.type)
    gen_retval_type = normalize_type(generator_token.return_value.type)
    if xml_retval_type != gen_retval_type:
        differences['return_type'] = (xml_retval_type, gen_retval_type)

    xml_args = tuple(f'{arg.name}:{normalize_type(arg.type)}' for arg in xml_token.args)
    generator_args = tuple(f'{arg.name}:{normalize_type(arg.type)}' for arg in generator_token.args)
    if xml_args != generator_args:
        differences['args'] = (xml_args, generator_args)

    return differences


def only_newest_token_versions(generator_functions: dict[str, list[Token]]) -> dict[str, Token]:
    """Return the highest-version token for each generator function name."""
    selected: dict[str, Token] = {}
    for name, versions in generator_functions.items():
        if not versions:
            continue  # TODO: This means broken data!
        selected[name] = max(versions, key=lambda token: token.version)
    return selected


def diff_xml_and_generator_functions(
    xml_functions: dict[Api, list[Token]],
    generator_functions: dict[str, list[Token]],
) -> None:
    """Diff functions from XML with those from legacy generator data."""
    xml_gl_tokens: list[Token] = xml_functions.get(Api.GL, [])  # TODO: Support other APIs (WGL, GLX, EGL) in the future.
    xml_tokens_by_name: dict[str, Token] = {token.name: token for token in xml_gl_tokens}
    generator_tokens_by_name = only_newest_token_versions(generator_functions)

    xml_names: set[str] = set(xml_tokens_by_name)
    generator_names: set[str] = set(generator_tokens_by_name)

    only_in_xml: list[Token] = [
        xml_tokens_by_name[name]
        for name in sorted(xml_names - generator_names)
    ]
    only_in_generator: list[Token] = [
        generator_tokens_by_name[name]
        for name in sorted(generator_names - xml_names)
    ]

    mismatches: list[tuple[str, TokenDifferencesType]] = []
    for name in sorted(xml_names & generator_names):
        differences = compare_function_tokens(xml_tokens_by_name[name], generator_tokens_by_name[name])
        if differences:
            mismatches.append((name, differences))

    if only_in_xml:
        print("####### Functions only present in XML (GL) #######")
        for token in only_in_xml:
            print(f"- {token.name}")

    if only_in_generator:
        print("####### Functions only present in generator (GL) #######")
        for token in only_in_generator:
            print(f"- {token.name}")

    if mismatches:
        print("####### Functions with signature differences (GL) #######")
        for name, differences in mismatches:
            print(f"- {name}")
            for field, values in differences.items():
                print(f"    {field}: xml={values[0]!r}, generator={values[1]!r}")


# ---------------------------------------------------------------------------
# Main function.
# ---------------------------------------------------------------------------

def main() -> None:
    """Update the OpenGL generator data based on gl.xml and similar files."""
    inspect_data: bool = False  # Disabled by default because of long output.

    enums_from_xml: dict[Api, list[EnumValue]]
    functions_from_xml: dict[Api, list[Token]]
    enums_from_xml, functions_from_xml = load_registries_and_extract_xml_data(_FILE_TO_API)

    # Detect differences between XML and existing generator data.
    generator_enums: dict[Api, list[EnumValue]] = get_enums()
    diff_xml_and_generator_enums(enums_from_xml, generator_enums)
    generator_functions: dict[str, list[Token]] = get_tokens(include_disabled=True)
    diff_xml_and_generator_functions(functions_from_xml, generator_functions)

    if inspect_data:
        # Inspect enum data per API.
        for api, api_enums in enums_from_xml.items():
            # print(f"\n\n\n        {api}        \n\n\n")
            # Old OpenGL backend will need few if any data updates, new backend won't
            # even store the data in intermediate form. This is why we don't bother
            # updating detect_duplicate_enum_values to support CANONICAL_NAME_OVERRIDES
            # from generate_gl.py or running it by default. It can be run manually
            # if we know we need to update enum data.
            # detect_duplicate_enum_values(api_enums)
            inspect_enums(api, api_enums)
        inspect_cross_file_enums(enums_from_xml)

        # Inspect function data per API.
        for api, api_functions in functions_from_xml.items():
            inspect_functions(api, api_functions)
            inspect_function_params(api, api_functions)
        check_function_groups_against_enums(functions_from_xml, enums_from_xml)

    # Generate output.
    mako_write('templates/meta_enums.py.mako', 'meta_enums.py', enums_by_api=enums_from_xml)
    mako_write('templates/meta_functions.py.mako', 'meta_functions.py', functions_by_api=functions_from_xml)


if __name__ == '__main__':
    main()
